### PR TITLE
add new vulnerability layers for zimbabwe

### PR DESCRIPTION
**Pull request by wadhwamatic**

### CODE REVIEW

**Comment by wadhwamatic** [comment]
surge deployment here: https://prism-demo-zwe.surge.sh/

**Comment by ericboucher** [comment]
@wadhwamatic maybe add a shortlist of the new layers in the PR description? Otherwise looks good, and thanks for the surge link!

**Comment by wadhwamatic** [comment]
Added the following layers under vulnerability:

- cereal insecurity (2021)
- 10-year average cereal insecurity
- 5-year average cereal insecurity
- poor food consumption
- borderline food consumption

Each of these layers is at admin 2 level and data is derived from the same local json file (public/data/zimbabwe/zim_fs_2021.json)

**Comment by wadhwamatic** [comment]
> @wadhwamatic maybe add a shortlist of the new layers in the PR description? Otherwise looks good, and thanks for the surge link!

@ericboucher - done!

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
