### PR TITLE
Feat/admin level data endpoints

### PR DESCRIPTION
**Pull request by erwagasore**
Added `/admin-level-data` endpoint which requires a `dataUrl` parameter as a source of `Admin Level Data`.

Our endpoint `/admin-level-data?dataUrl=https://api.hungermapdata.org/v1/foodsecurity/country/MOZ/region?date_start=2021-12-15` parses primitive data into similar format we use on the `frontend`

from
```json
[
  {
    "country": {"id": 170, "name": "Mozambique", "iso3": "MOZ", "iso2": "MZ"}, "region": {"id": 900948, "name": "Cabo Delgado", "population": 2107193}, 
    "date": "2021-10-01", 
    "dataType": "SURVEY", 
    "metrics": {
      "fcs": {"people": 661806, "prevalence": 0.3140699499286492}, 
      "rcsi": {"people": 669016, "prevalence": 0.31749156342110096},
      "healthAccess": {"people": 778837, "prevalence": 0.38681952501275707},
      "marketAccess": {"people": 930978, "prevalence": 0.44180955422687906},
      "livelihoodCoping": {"people": 1235764, "prevalence": 0.5864503156568952}
    }
  },
  ...
]
```
to 
```json
{
  "DataList": [
    {
      "date": "2021-10-01",
      "fcs_people": 661806,
      "fcs_prevalence": 0.3140699499286492,
      "healthAccess_people": 778837,
      "healthAccess_prevalence": 0.38681952501275707,
      "livelihoodCoping_people": 1235764,
      "livelihoodCoping_prevalence": 0.5864503156568952,
      "marketAccess_people": 930978,
      "marketAccess_prevalence": 0.44180955422687906,
      "mvam_Code": 900948,
      "mvam_Name": "Cabo Delgado",
      "population": 2107193,
      "rcsi_people": 669016,
      "rcsi_prevalence": 0.31749156342110096
    },
    ...
  ]
}
```

We have started with MVAM HungerMapData, but defined a structure to handle data from other sources as the need arises.

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@erwagasore - is this ready for testing? If not, keep it as a draft until ready.

**Comment by wadhwamatic** [comment]
@erwagasore - I tried to run an exposure analysis for Myanmar and got an error:
**Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'boundary')**

I thought it might relate to a missing 'isPrimary' layer but adding that didn't make a difference. I also tried an exposure analysis for Tajikistan, which for the moment just has 1 admin boundary layer but received the same error.

cc: @ericboucher

**Comment by ericboucher** [comment]
@wadhwamatic @erwagasore is this really compute heavy? This seems like a pretty straightforward parsing/aggregation of data. Why do we need this to happen within the python API?

**Comment by wadhwamatic** [comment]
also relates to https://github.com/WFP-VAM/prism-frontend/issues/349

**Comment by ericboucher** [comment]
As discussed in https://github.com/WFP-VAM/prism-frontend/issues/349, I think we should try to achieve this at build time on the frontend side. Unless I am missing something, I don't think that there is a need to add a dependency to the prism-api for this step.

**Review by ericboucher — CHANGES_REQUESTED** [review]
Let's do this in the frontend directly as this is not compute heavy.

**Comment by wadhwamatic** [comment]
This PR is no longer valid. The functionality should be moved to the frontend

**Pull request closed without merging**
