### PR TITLE
initial configuration for Ukraine demo

### PR DESCRIPTION
**Pull request by wadhwamatic**
This PR creates an initial configuration for PRISM Ukraine for demonstration purposes. This branch incorporates the time-series chart trend feature included in PR https://github.com/WFP-VAM/prism-frontend/pull/453 and the bounding box / zoom level restriction feature in PR https://github.com/WFP-VAM/prism-frontend/pull/462

Surge demo page: https://prism-demo-ukr.surge.sh/

Screen Shot 2022-05-05 at 20 56 18

### CODE REVIEW

**Comment by ericboucher** [comment]
@wadhwamatic let's deploy a surge when you get a chance?

**Comment by wadhwamatic** [comment]
> @wadhwamatic let's deploy a surge when you get a chance?

@ericboucher - sorry, forgot to add that to the PR earlier: https://prism-demo-ukr.surge.sh/

**Comment by ericboucher** [comment]
@wadhwamatic is this ready to be merged?

**Comment by wadhwamatic** [comment]
> @wadhwamatic is this ready to be merged?

actually, not yet.. it has dependency on https://github.com/WFP-VAM/prism-frontend/pull/462

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
