### PR TITLE
Allow custom label on Legend

### PR DESCRIPTION
**Pull request by reed1**
For issue #320

### CODE REVIEW

**Comment by ericboucher** [comment]
@reed1 looks good! Can you add a few screenshots and example explicating how the app is changing?

**Comment by wadhwamatic** [comment]
Looks good @reed1. As Eric mentioned, next time add some details on the expected behavior and how to test.
From my side, I tested by adding label attributes to a layer and making the 'stops' for values more concise than previously. Specifically, for Myanmar's 'improved sanitation' layer:

    "legend": [
      { "label": "<20%", "value": "0", "color": "#a50f15" },
      { "label": "21 to 40%", "value": "21", "color": "#de2d26" },
      { "label": "41 to 60%", "value": "41", "color": "#fb6a4a" },
      { "label": "61 to 80%", "value": "61", "color": "#fcae91" },
      { "label": "81 to 100%", "value": "81", "color": "#fee5d9" }
    ],

The result is as expected:
Screen Shot 2021-12-02 at 19 03 03

**Review by wadhwamatic — APPROVED** [review]
See earlier comment. Requesting a review from @JorgeMartinezG too.

**Comment by erwagasore** [comment]
Look straight forward @reed1 minor comment would be to name the function `legendItemLabel` to `getLegendItemLabel` to just signal that this is a function. Again it is a minor.

**Review by erwagasore — APPROVED** [review]

**Comment by ericboucher** [comment]
@reed1 still worth renaming the function as @erwagasore suggested I think.

**Comment by ericboucher** [comment]
@reed1 still worth renaming the function as @erwagasore suggested I think.

**Comment by wadhwamatic** [comment]
> @reed1 still worth renaming the function as @erwagasore suggested I think.

Sorry about that. I created a new issue and assigned it to @reed1 . https://github.com/WFP-VAM/prism-frontend/issues/331

**Pull request merged**
