### PR TITLE
Use adminCode instead of names for analysis groupBy

### PR DESCRIPTION
**Pull request by wadhwamatic**
This PR addresses https://github.com/WFP-VAM/prism-frontend/issues/388. @ericboucher implemented a fix to group by admin code rather than admin name. 
This PR also includes RBD config updates which surfaced the group by issue.

### CODE REVIEW

**Comment by wadhwamatic** [comment]
@ericboucher - I tested this in multiple deployments and found no issues except for what I noted here https://github.com/WFP-VAM/prism-frontend/issues/397 but I think that is something to do with the admin boundaries and/or stats API rather than this fix

**Comment by tdlinh2712** [comment]
@ericboucher the issue is not because of the sort function, it's because there are multiple rows in the table have the same name (ie Ampil), and we were using location names as the row keys, hence the rows have non-unique keys. To fix this we can change the key to some autogenerated values/find another attribute that have unique values, or make the location names unique. Why are the names repeated in with 10-day rainfall + IDPoor?

**Comment by wadhwamatic** [comment]
> @ericboucher the issue is not because of the sort function, it's because there are multiple rows in the table have the same name (ie Ampil), and we were using location names as the row keys, hence the rows have non-unique keys. To fix this we can change the key to some autogenerated values/find another attribute that have unique values, or make the location names unique. Why are the names repeated in with 10-day rainfall + IDPoor? image

@tdlinh2712 - yeah, the problem is that non-unique names is possible if we're not concatenating all admin levels. We didn't have all levels included in the Cambodia boundary file so couldn't specify the names for the hierarchy. I went ahead and generated a file that now includes names at all levels and updated the Cambodia configuration in this branch. That fixes the problem.  I don't think we should have this issue if it's clearly documented that names must be unique either on their own or through concatenation of levels

**Comment by wadhwamatic** [comment]
@ericboucher - I tested the Mongolia issue (https://github.com/WFP-VAM/prism-frontend/issues/398) on this branch. Looks good now, thanks.

**Comment by ericboucher** [comment]
So does this seem good to you @wadhwamatic ? Good to merge?

**Comment by wadhwamatic** [comment]
> Looks all good now @wadhwamatic ? Good to merge?

@ericboucher - yes good to go. thanks

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
