### PR TITLE
Display layer group name in navbar and independent layers for analysis

### PR DESCRIPTION
**Pull request by JorgeMartinezG**
**Changes**

- Listing secondary layers within analysis dropdown menu.
- Display group name instead of main layer name within navbar menu.

PR deployed to http://homeless-giraffe.surge.sh/

### CODE REVIEW

**Review by dubwalla — APPROVED** [review]
Looks good from my perspective. We've got a minor issue where some storms don't have all three layers populated. As discussed with Jorge, this will be addressed in GeoServer. It's not a PRISM issue

**Comment by ericboucher** [comment]
This is not working as expected in the surge. If you unselect the Tropical Storm layer, a few of the underlying layers actually stay on, see screenshot:

Screen Shot 2021-04-15 at 11 14 42 PM

**Comment by JorgeMartinezG** [comment]
@ericboucher  Thanks for flagging. I included the fix in https://github.com/WFP-VAM/prism-frontend/pull/161/commits/f687807c9a821f918eec64e3e84423941c0a4e93 and deployed to same url:

**Comment by JorgeMartinezG** [comment]
BTW I just made a force-push of the last commit. A comment was missing

**Review by ericboucher — APPROVED** [review]

**Pull request merged**
