### PR TITLE
update css for app container

### PR DESCRIPTION
**Pull request by hav142**
For issue #411

### CODE REVIEW

**Comment by hav142** [comment]
> @hav142 on what browser are you having this issue?

@ericboucher I tried on firefox and chrome

**Comment by ericboucher** [comment]
I am not seeing this, can you deploy your version to surge.sh or something so that we can compare?

Do you also see the issue you're mentioning on https://prism-mongolia.org/ ? Can you make sure that you are not zoomed in?

Also, what's with the image changes? Let's focus on the css container issue for this PR

**Comment by reed1** [comment]
I think the issue was because of `#app` container addition for login feature

The https://prism-mongolia.org/ doesn't have that container yet, but these have:
- https://prism-demo-moz.surge.sh/
- https://prism-demo-moz.surge.sh/

This is this branch deployment:
https://prism-css-container.surge.sh/

For image changes, `yarn test` should have REACT_APP_COUNTRY variable unset so it will use 'myanmar' as default country (config/index.ts) to produce test snapshots. I think @hav142 might have set it to 'mozambique'. Should we revert the commit?

**Comment by hav142** [comment]
Sorry I just realized about the country config as the cause of the snapshot file change. thanks @reed1 for mentioning

**Review by ericboucher — APPROVED** [review]

**Comment by ericboucher** [comment]
Ok sorry, I did not have the context. Looks good, thanks for the update.

**Pull request merged**
